---
- name: install docker
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ pdns_admin__docker_packages }}"
- name: create docker directory
  file:
    path: "{{ pdns_admin__docker_compose_dir }}"
    mode: '0644'
    state: directory
    recurse: true
- name: create docker compose file
  template:
    dest: "{{ pdns_admin__docker_compose_dir }}/docker-compose.yml"
    mode: 0644
    src: docker/docker-compose.yml.j2
  notify: pdns_admin__docker_restart
